# Generated by Django 3.2.7 on 2021-11-16 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sudentapp', '0016_auto_20211111_1512'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('KG', 'килиграмм'), ('G', 'грамм'), ('U', 'штук')], max_length=2)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sudentapp.food')),
                ('fridge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storageapp.fridge')),
            ],
        ),
        migrations.DeleteModel(
            name='Perosne',
        ),
    ]
