# Generated by Django 3.2.7 on 2021-10-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudentapp', '0003_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
