# Generated by Django 3.2.7 on 2021-10-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudentapp', '0004_alter_dish_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
