# Generated by Django 3.2.7 on 2021-10-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudentapp', '0006_auto_20211028_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='typ',
            field=models.CharField(choices=[('S', 'Суп'), ('G', 'Гарнир')], default='S', max_length=2),
            preserve_default=False,
        ),
    ]
