# Generated by Django 3.2.7 on 2021-10-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudentapp', '0007_dish_typ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='dish',
        ),
    ]
