# Generated by Django 3.2.7 on 2021-10-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudentapp', '0008_remove_ingredient_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='dish',
            field=models.ManyToManyField(to='sudentapp.Dish'),
        ),
    ]
