# Generated by Django 3.2.7 on 2021-10-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudentapp', '0010_auto_20211028_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='dish',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dish',
            field=models.ManyToManyField(to='sudentapp.Dish'),
        ),
    ]
