# Generated by Django 3.2.7 on 2021-11-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudentapp', '0015_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.CharField(blank=True, max_length=255, verbose_name='slug'),
        ),
    ]
