# Generated by Django 3.2.7 on 2021-11-18 15:56

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sudentapp', '0018_alter_dish_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=''),
        ),
    ]
